@startuml 02_usecase_diagram
title "Use-Case диаграмма: Сценарии использования системы поиска фактологических противоречий"

left to right direction

actor "Пользователь" as User

rectangle "RAG Knowledge Base System" {

  usecase "Загрузить документ" as UC1
  usecase "Проверить на противоречия" as UC2
  usecase "Просмотреть отчёт" as UC3

  usecase "Извлечь атомарные утверждения" as UC1_1
  usecase "Разбить текст на чанки" as UC1_1_1
  usecase "Извлечь атомартные утверждения" as UC1_1_2
  usecase "Деконтекстуализировать факты" as UC1_2
  usecase "Найти местоимения и сущности" as UC1_2_1
  usecase "Заменить местоимения" as UC1_2_2
  usecase "Сохранить атомарное утверждение" as UC1_3
  usecase "Сгенерировать вектор" as UC1_3_1
  usecase "Сохранить в векторную БД" as UC1_3_2

  usecase "Найти факты по теме" as UC2_1
  usecase "Сформировать пары" as UC2_2
  usecase "Классифицировать через NLI" as UC2_3
  usecase "Отильтровать по уверенности" as UC2_4

  UC1 ..> UC1_1 : <<include>>
  UC1 ..> UC1_2 : <<include>>
  UC1 ..> UC1_3 : <<include>>

  UC2 ..> UC2_1 : <<include>>
  UC2 ..> UC2_2 : <<include>>
  UC2 ..> UC2_3 : <<include>>
  UC2 ..> UC2_4 : <<extend>>

  UC1_1 ..> UC1_1_1 : <<include>>
  UC1_1 ..> UC1_1_2 : <<include>>
  UC1_2 ..> UC1_2_1 : <<include>>
  UC1_2 ..> UC1_2_2 : <<include>>
  UC1_3 ..> UC1_3_1 : <<include>>
  UC1_3 ..> UC1_3_2 : <<include>>

  ' UC1 ..> UC1_1 : <<include>>
  ' UC2 ..> UC2_1 : <<include>>
  ' UC2 ..> UC2_2 : <<include>>
  ' UC3 ..> UC3_1 : <<include>>
  ' UC3 ..> UC3_2 : <<include>>
  ' UC4 ..> UC4_1 : <<include>>
  ' UC4 ..> UC4_2 : <<include>>
  ' UC4 ..> UC4_3 : <<include>>
  ' UC4 ..> UC4_4 : <<extend>>
}

User --> UC1
User --> UC2
User --> UC3

@enduml